blank_issues_enabled: false
contact_links:
    - name: Installation and development guide
      url: https://github.com/ProtonDev-sys/ProtonnCord#readme
      about: Protonn Cord installation, updates, testing, and project information
